### ISSUE TITLE
Is there tutorial on how to combine fonts?

### ISSUE THREAD

**Issue by dabeibao** [muhac/monaco-fira-ligatures-nerd-font#1]
Hi @muhac thanks for your work. 
Is there tutorial on how to make fonts? 
Really like the 'MonacoFiraNerd' font, but I want to replace MonacoB with origianl Monaco.

**Comment by muhac** [comment]
Hi @dabeibao

> Is there tutorial on how to make fonts?

You'll need a font editor to do so. I used [fontforge](https://github.com/fontforge/fontforge). There is a guide on their website which may help. Replacement is relatively simple :)

> I want to replace MonacoB with original Monaco.

PR for a Light font is welcomed!

Though the author of MonacoB said that the font was 20% bolder, I don't see significant changes compared to Monaco. Maybe you can double check it in your code editor before you do real work on editing fonts.

**Comment by muhac** [comment]
> the author of MonacoB said that the font was 20% bolder

Just read [that readme](https://github.com/vjpr/monaco-bold/tree/b77db4b6fc2e9df074f8db59cead862d7068e3d7#:~:text=MonacoB%20%2D%20bold%20(20%25%20transform)) again. I believe MonacoB is exactly the original Monaco. MonacoB Bold is the bolder one.

**Comment by dabeibao** [comment]
@muhac Thanks a lot!
Will have a try!

**Comment by dabeibao** [comment]
> > the author of MonacoB said that the font was 20% bolder
> 
> Just read [that readme](https://github.com/vjpr/monaco-bold/tree/b77db4b6fc2e9df074f8db59cead862d7068e3d7#:~:text=MonacoB%20%2D%20bold%20(20%25%20transform)) again. I believe MonacoB is exactly the original Monaco. MonacoB Bold is the bolder one.

I carefully compared two versions. Yes they have same weight and should be the same font. 
The only difference is the original one (the first figure) has smaller gap. 


![Monaco](https://github.com/user-attachments/assets/bbd10080-1c4c-4a7d-84c3-cff90aba3339)
![MonacoFiraNerd](https://github.com/user-attachments/assets/9b9e9e90-f094-414e-8962-4506c595378d)

**Comment by muhac** [comment]
> The only difference is the original one (the first figure) has smaller gap.

That's because Fira Code is wider - have to modify the gap to fit.
